### ISSUE TITLE
Doesn't install on ST3 through package manager

### ISSUE THREAD

**Issue by PhilCoggins** [danielfrey/sublime-cucumber-step-finder#16]
ST3, OSX 10.10 (Yosemite)
I attempted to install this package through package manager and it doesn't work.

1) Installed ST3 through package manager
2) Attempt Super + y to search cucumber steps, nothing happens, nothing in console
3) Attempt ctrl + super + m to match a step definition, nothing happens, nothing in console
4) Attempt restart and retry steps 2 + 3, nothing happens.
5) Try to find package settings under Sublime Text -> Preferences -> Package settings, nothing there references cucumber step finder.

What's going on?

**Comment by markalfred** [comment]
@PhilCoggins currently, this plugin doesn't read settings from your user settings (`Packages/User/Preferences.sublime-settings`). As a workaround, you can define the above settings in a new file `Packages/User/CucumberStepFinder.sublime-settings` and this should work correctly.
