### ISSUE TITLE
Rethink Super+MouseClick hotkey, or limit it to feature files

### ISSUE THREAD

**Issue by markalfred** [danielfrey/sublime-cucumber-step-finder#20]
Super+MouseClick is used to add a new cursor in the clicked position. Alt+Click isn't tied to anything by default for OSX users as far as I know.

**Comment by danielfrey** [comment]
@markalfred: Thanks for the hint! I changed it to [alt+click]

**Comment by DSegal92** [comment]
This remapping breaks column select, please choose another key binding

**Comment by danielfrey** [comment]
@DSegal92: What is column select? I can't see an effect by alt-Clicking anywhere in my files without my binding. Is it a special package you use?

**Comment by DSegal92** [comment]
Column select is built into Sublime Text as far as I'm aware, it's used by alt/option click & dragging, not just clicking https://www.sublimetext.com/docs/2/column_selection.html

**Comment by markalfred** [comment]
Yikes, good catch @DSegal92. My apologies @danielfrey

**Comment by danielfrey** [comment]
@DSegal92 and @markalfred:
Would shift+super or shift+alt be an alternative? Is there a way, to limit a mouse-map to a file-type?
I couldn't find a hint about that.

**Comment by DSegal92** [comment]
Looks like you might be able to scope it by file type http://sublimetext.userecho.com/topic/21146-key-binding-context-to-only-react-on-eg-python-code/

**Comment by markalfred** [comment]
@danielfrey I'd be happy to tackle scoping, just let me know so we don't double effort. If it helps, I have a helper method [here](https://github.com/markalfred/sublime-gherkin-formatter/blob/d38251916cef4b9b4663a94a9b1f752fc6bc9820/sublime-gherkin-formatter.py#L9) that either of us could duplicate.
