### ISSUE TITLE
Add Open in New Pane setting

### ISSUE THREAD

**Issue by vinu91** [danielfrey/sublime-cucumber-step-finder#21]
The behaviour of Opening a match in a new pane had been added via this commit

https://github.com/danielfrey/sublime-cucumber-step-finder/commit/87b85c4bf9b7aa15ac0a81adb5f4b3e5f737a9ff

Please consider making this a setting as the previous implementation better suited my work style and perhaps for some other devs as well who prefer to work in a single pane mode.

**Comment by dchersey** [comment]
I second this request!

**Comment by PatrickKing** [comment]
+1 for this.

Thanks for your work on this package!

**Comment by danielfrey** [comment]
There's a new version where you may configure the opening in  new pane in the settings.
The setting is called "open_in_different_pane".
Please let me know, if this satisfies your needs. 
The new version (0.3.6) should be available in the package-control soon.

**Comment by dchersey** [comment]
Thank you!!

**Comment by PatrickKing** [comment]
Thank you! 

For future readers who want to use this setting, you can add this to your Preferences.sublime-settings file:

```
  "CucumberStepFinder":
  {
    "open_in_different_pane": false
  }
```

**Comment by ghost** [comment]
Thank you
