### ISSUE TITLE
Doesn't work with Sublime Text 2 + Windows 7

### ISSUE THREAD

**Issue by dkirrane** [danielfrey/sublime-cucumber-step-finder#22]
Both Key bindings and Menu Options 'Find > Find Cucumber Step' & 'Find > Match Cucumber Step'  don't do anything on Windows 7 using Sublime Text 2.

Windows 7 Professional 64-bit (6.1, Build 7601)

**Comment by danielfrey** [comment]
Do you see any errors in the console?
Are your step files in the directory configured in the settings? See https://github.com/danielfrey/sublime-cucumber-step-finder#configuration

**Comment by danielfrey** [comment]
I close this issue since it seems to be a configuration issue and there is no feedback
