### ISSUE TITLE
the button override redo action

### ISSUE THREAD

**Issue by wendy0402** [danielfrey/sublime-cucumber-step-finder#25]
You should change the shortcut keys to execute step finder, because `[command] + Y` has been reserved by step redo action, try to use  `[command] + shift+ Y` I guess

**Comment by danielfrey** [comment]
Since every key seems to be preoccupied by some functionality or plugin I suggest to override the command in your personal key-bindings file like I suggested here:
https://github.com/danielfrey/sublime-cucumber-step-finder#usage

`{ "keys": ["ctrl+shift+alt+y"], "command": "cucumber_step_finder" }`
